let
    Source = Csv.Document(File.Contents("C:\Users\Muhsin\Downloads\loan.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"ListingNumber", type text}, {"Term", Int64.Type}, {"LoanStatus", type text}, {"BorrowerAPR", type number}, {"BorrowerRate", type number}, {"ProsperRating", type text}, {"ProsperScore", Int64.Type}, {"BorrowerState", type text}, {"Occupation", type text}, {"EmploymentStatus", type text}, {"IsBorrowerHomeOwner", type logical}, {"IncomeRange", type text}, {"LoanOriginalAmount", Int64.Type}, {"LoanOriginationDate", type date}, {"Listing_Category", type text}}),
    #"Inserted Division" = Table.AddColumn(#"Changed Type", "Division", each [Term] / 12, type number),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Division",{"", "ListingNumber", "Term", "Division", "LoanStatus", "BorrowerAPR", "BorrowerRate", "ProsperRating", "ProsperScore", "BorrowerState", "Occupation", "EmploymentStatus", "IsBorrowerHomeOwner", "IncomeRange", "LoanOriginalAmount", "LoanOriginationDate", "Listing_Category"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Division", "Loan Term (Years)"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Summary Loan Status", each if Text.Contains([LoanStatus], "Past") then "Past Due Date" else [LoanStatus]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Summary Loan Status", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"", "Term"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"ProsperScore", type text}}),
    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type2", "Loan Status Reviewed", each if Text.Contains([LoanStatus], "Past") then "Past Due" else [LoanStatus]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Loan Status Reviewed", type text}})
in
    #"Changed Type3"